### ISSUE TITLE
Discuss: use of totaltasks variable.

### ISSUE THREAD

**Issue by grg121** [angrykoala/gaucho#132]
while adding bottom-bar to count running tasks and total tasks we saw two differents views of the purpose of that variable... Should it count all gaucho tasks in any suite or only at the active suite?

I thought we should count only visible tasks but maybe it would be more interesting to know total tasks in the whole app in order to have an idea of the size of the project without move around the differents suites.

Maybe, as bottom-bar is a little empty, we could use both. Total tasks and visible tasks or active tasks or something that way.

**Comment by angrykoala** [comment]
By design, each suite is limited to 8 tasks, so usually you would be able to see how many tasks are running. I think is much more useful to have a count of total tasks running in gaucho.

Both counts may be added, (e.g `Total Tasks: 3/10`) However, I think it may add some confusion to what those numbers are.

To make the app as simple as possible, I think is better to reduce the number on information displayed in the bottom bar. In fact, we could show simply: `Tasks <running>/<total>`

Another option, is to show the number of running tasks in the name of the suite:

`Suite A (2)` but it may be confusing...
