### ISSUE TITLE
Sortablejs warning

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#196]
![screenshot from 2017-10-14 19-05-25](https://user-images.githubusercontent.com/5960567/31577628-b699ebf8-b112-11e7-98ed-08b091faa7d5.png)

Sortable library used for tasks reordering throws a warning, probably not important, but worth investigating related to #156

**Comment by angrykoala** [comment]
may be related to #202

**Comment by rkomiyama** [comment]
It doesn't seem to be related to #202, since I made a quick fix for `Sortable.js` and that warning is still there.

I've put up a [PR](https://github.com/RubaXa/Sortable/pull/1202) in the `Sortable` repo for the fix. If they aren't okay with those changes, we could use our own fork of their project and make the appropriate changes.

**Comment by angrykoala** [comment]
@rkomiyama Thanks for digging into this. I don't think it is worth it making out own fork (this is just a minor issue), but it would be awesome if they accept your PR so we could get rid of this warning.

Please keep this issue updated with any news about this

**Comment by angrykoala** [comment]
This seems to be a problem of Sortable library, closed for now
