### ISSUE TITLE
Forcing reflow warning message when opening modal

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#202]
![screenshot from 2017-10-16 00-17-57](https://user-images.githubusercontent.com/5960567/31589787-8720696a-b207-11e7-8747-4e0cfe45b842.png)
This warning message appears when a modal (using sweetalert2) is opened.

Investigate why this message appears

**Comment by rkomiyama** [comment]
[Here's some reading material on forced reflow.](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid-forced-synchronous-layouts)

This is what I'm seeing in my dev tools:
<img width="676" alt="screen shot 2017-10-26 at 5 26 53 pm" src="https://user-images.githubusercontent.com/347483/32078006-49edf23c-ba73-11e7-8b41-59d0696e3ef6.png">

**Comment by angrykoala** [comment]
Hi @rkomiyama , thanks for taking the time to get that info. Because this seems to be caused by a library (materialize) do you recokn there is a way to improve this?

**Comment by rkomiyama** [comment]
There probably is a way to improve Materialize. There are a handful of closed issues related to reflow caused by Materialize, but I didn't see any solutions offered by anyone. It certainly wouldn't hurt to ask them for help, but I'm assuming that this is something we'll probably have to figure out by ourselves.

**Comment by angrykoala** [comment]
No longer relevant due to major refactor and change of libraries
