### ISSUE TITLE
Make PKGBUILD for Arch Linux (git version)

### ISSUE THREAD

**Issue by aledomu** [angrykoala/gaucho#225]
I was thinking about making an Arch's build script to automatically package gaucho directly from this repo. I could make another PKGBUILD for stable releases when 0.4 is released.

This script would go in this repository, so if you agree with writing the script for the git version, a PR will follow soon.

**Comment by angrykoala** [comment]
Hi @aledomu 
What kind of packages are generated by PKGBUILD?

Keep in mind that for packaging we will be using [electron-builder](https://github.com/electron-userland/electron-builder) to create the packages. Unless strictly necessary I would like to avoid having separate pipelines for build.

afaik, Arch uses `pacman` as package manager, which is among the supported packages from electron builder:
```
snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir
```

If you want to add support for it, instead of making a separate PKGBUILD, try modifying the `package.json` file in `dev` (https://github.com/angrykoala/gaucho/blob/dev/package.json) to add pacman (or any other) to the building process according to the electron-builder docs.

Please, check if the resulted package after running `npm run dist` is working in Arch. 
If it is not working, we may consider adding a separate pipeline with a script to provide support for that platform.

Thanks

**Comment by aledomu** [comment]
Ok, I'll tweak the `package.json` file so it builds Arch packages. We'll discuss later all the stuff about the PKGBUILDs.

**Comment by angrykoala** [comment]
ok

**Comment by angrykoala** [comment]
#233 merged, I assume this is not enough to close this ticket, what else do we have to do?

**Comment by aledomu** [comment]
I initially thought it was a good idea to put the PKGBUILD in this repo, but seeing how other people accomplish the same task I think it's better to just send it to AUR and the one who wrote that is who maintains it. So it's safe to close this as I see nothing more to do here.

**Comment by angrykoala** [comment]
Adding wontfix tag as no changes were made as part of this issue
