### ISSUE TITLE
Support for 32 bits

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#238]
With @aledomu changes in PR #233 , I'm considering if it is worth it to support 32 bits as a default.

Maybe we could have a separate build option for 32 bits machines so it is possible to compile from source for people who really need 32 bits, this way we could avoid having too many build artifact in each release

**Comment by aledomu** [comment]
I was thinking about supporting it as a default as well, but reached the conclusion that 32 bits could be considered legacy nowadays (see what distros like Ubuntu are doing).
Yeah, I could enable separate build options for both architectures. I see that the build-electron options do the same thing as the dist ones, so that might be something to tackle too.

**Comment by angrykoala** [comment]
I already removed build-electron options

Please, check passing arguments to npm scripts, as the package.json may be simplified by doing this ( avoid having a lot of repeated rules)

**Comment by aledomu** [comment]
Will check.

**Comment by aledomu** [comment]
With the 32-bit build config and scripts already implemented, I think we can close this issue.
