### ISSUE TITLE
feature request:  add auto scheduler

### ISSUE THREAD

**Issue by badrelmers** [angrykoala/gaucho#381]
Hi,
Thank you for this excellent work.
Can you add an option to auto schedule the jobs? something like run every minute or every day.

Thank you.

**Comment by angrykoala** [comment]
hi @badrelmers

Scheduling support is a bit limited in Gaucho. I'm thinking on adding a "repeat" checkbox in the current "Schedule" menu so if it is clicked, it restarts the scheduling time automatically when the task is executed. Would this work for you?

As an example ofhow would this work:
![Screenshot from 2020-03-27 01-29-06](https://user-images.githubusercontent.com/5960567/77709204-9dd0b880-6fca-11ea-9aa6-7dddfa3e796d.png)

If the box "repeat" is clicked, the task will be executed after 1 hour (3600 seconds), and then again every hour until manually stopped

Thoughts?

**Comment by badrelmers** [comment]
Hi,
yes it is perfect, I like it. thank you very much.

**Comment by angrykoala** [comment]
@badrelmers Ok, I'm not sure when I'll be able to get to this, but I'll keep in mind for the next

**Comment by badrelmers** [comment]
Ok, thank you.

**Comment by angrykoala** [comment]
Due to some limitations on how tasks work, the following will be the exact behavior implemented:

1. On schedule menu, the option repeat may be set
2. The task will be executed after given time (e.g. 5 seconds)
   * If the scheduling is manually cancelled it won't be re-executed
3. The task will run normally
    * If the task is stopped manually it won't be re-executed.
4. **After** the task is finished (or errored), it will be re-scheduled again (5 seconds)
    * This is done to avoid a task being executed before finished (Gaucho doesn't support handling of concurrent executions of same tasks) and avoid a task being in execution and scheduling at the same time

Keep in mind that this behavior **won't** reliably execute a given task every n seconds (it will depend on how long the task takes to be executed). Also, remember that the scheduling itself is prone to minor timing errors of up to 2 seconds that may be carried over subsequent executions and re-scheduling and that the scheduling will only be executed as long as Gaucho is open.

@badrelmers I think this behavior is good enough for most cases (and I hope it solves yours), if you, however, need a reliable way of executing something every n seconds / hours, I recommend using a more appropriate tool such as [cron](https://linuxconfig.org/linux-crontab-reference-guide)

This behaviour will be available in next version (either 0.9 or 1.0). If you need it before release, you can also compile Gaucho on `dev` branch following these [instructions](https://github.com/angrykoala/gaucho#development)

**Comment by badrelmers** [comment]
I just tested the timer option , thank you very much for your time.
in fact it is difficult to use , because the timer is not per task but is a general timer, all tasks will have the same timer. I hope you can make the timer per task
Thank you

**Comment by angrykoala** [comment]
Hi @badrelmers 
The timer is actually per task, right click on a task > Schedule

Sorry for it not being obvious, I'm planning on improving overall Gaucho docs at some point  to explain all of this

**Comment by badrelmers** [comment]
OMG I tested everything the last time and did not see it. it rocks :+1: 
Thank you very much.
